server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:bookstoredb
    driver-class-name: org.h2.Driver
    username: sa
    password:
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:sql/init.sql
#      schema-locations: classpath:sql/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
